## What is UDP?



UDP is a way for two devices to send short messages to each other over a network.

Think of it like throwing a postcard
 -You write a short message
You write the destination address
You throw it into the network
You don’t wait for a reply
You don’t know if it arrives

But it is very fast

That is UDP.

# UDP Listener (Simple)

We create the UDP socket once and bind it to a port.
Then we use another cell to read from it.

In [1]:
import socket

UDP_IP = "0.0.0.0"
UDP_PORT = 8050   # <-- change to a free port, and use same on Arduino

# If a socket already exists in this notebook, close it first
try:
    sock.close()
except NameError:
    pass
except OSError:
    pass

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))

print(f"Listening for UDP on {UDP_IP}:{UDP_PORT}")

Listening for UDP on 0.0.0.0:8050

In [2]:
import pandas as pd
from datetime import datetime

df = pd.DataFrame(columns=["timestamp", "sender", "value"])
df

Empty DataFrame
Columns: [timestamp, sender, value]
Index: []

## Read one packet + log to pandas

In [3]:
print("Waiting for 1 UDP message...")

data, addr = sock.recvfrom(4096)          # this blocks until a packet arrives
text = data.decode(errors="ignore").strip()
sender = f"{addr[0]}:{addr[1]}"
timestamp = datetime.now().isoformat()

print("Received:", text, "from", sender)

df.loc[len(df)] = [timestamp, sender, text]
df.tail()

Waiting for 1 UDP message...
Received: -0.03 from 192.168.1.238:8000

                    timestamp              sender  value
0  2025-12-03T21:57:56.200598  192.168.1.238:8000  -0.03

In [ ]:
df.to_csv("udp_data.csv", index=False)
print("Saved to udp_data.csv")

In [39]:
sock.close()
print("Socket closed")

Socket closed

---

# Continuous UDP listener

- runs in the background
- keeps listening and logging
- stores everything in a pandas DataFrame

## Create the DataFrame

In [ ]:
import pandas as pd
from datetime import datetime

df = pd.DataFrame(columns=["timestamp", "sender", "value"])
df

## Start a continuous UDP listener in the background

In [4]:
import socket
import threading

UDP_IP = "0.0.0.0"
UDP_PORT = 8050  # choose a port and use the same on Arduino / sender

print(f"Starting UDP listener on {UDP_IP}:{UDP_PORT} ...")

# If an old socket exists, try to close it
try:
    sock.close()
except NameError:
    pass
except OSError:
    pass

# Create and bind socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))

running = True  # flag to control the listener thread

def udp_listener():
    global df, running
    print("UDP listener thread is running...")

    while running:
        try:
            data, addr = sock.recvfrom(4096)  # blocking: waits for data
            text = data.decode(errors="ignore").strip()
            sender = f"{addr[0]}:{addr[1]}"
            timestamp = datetime.now().isoformat()

            print(f"[{timestamp}] {sender} -> {text}")

            # append to DataFrame
            new_row = {
                "timestamp": timestamp,
                "sender": sender,
                "value": text
            }
            df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

        except OSError:
            # socket closed → exit loop
            break
        except Exception as e:
            print("Error receiving UDP:", e)
            break

listener_thread = threading.Thread(target=udp_listener, daemon=True)
listener_thread.start()

Starting UDP listener on 0.0.0.0:8050 ...
UDP listener thread is running...

[2025-12-03T21:58:16.625169] 192.168.1.238:8000 -> 0.34
[2025-12-03T21:58:16.811935] 192.168.1.238:8000 -> 0.30
[2025-12-03T21:58:17.006719] 192.168.1.238:8000 -> 0.29
[2025-12-03T21:58:17.195285] 192.168.1.238:8000 -> 0.20
[2025-12-03T21:58:17.388594] 192.168.1.238:8000 -> 0.27
[2025-12-03T21:58:17.577906] 192.168.1.238:8000 -> 0.29
[2025-12-03T21:58:17.764965] 192.168.1.238:8000 -> 0.21
[2025-12-03T21:58:17.950493] 192.168.1.238:8000 -> 0.30
[2025-12-03T21:58:18.132813] 192.168.1.238:8000 -> 0.35
[2025-12-03T21:58:18.329459] 192.168.1.238:8000 -> 0.28
[2025-12-03T21:58:18.509595] 192.168.1.238:8000 -> 0.31
[2025-12-03T21:58:18.698817] 192.168.1.238:8000 -> 0.37
[2025-12-03T21:58:18.890658] 192.168.1.238:8000 -> 0.38
[2025-12-03T21:58:19.072832] 192.168.1.238:8000 -> 0.32
[2025-12-03T21:58:19.265722] 192.168.1.238:8000 -> 0.32
[2025-12-03T21:58:19.458756] 192.168.1.238:8000 -> 0.23
[2025-12-03T21:58:19.650025] 192.168.1.238:8000 -> 0.31
[2025-12-03T21:58:19.839851] 192.168.1.238:8000 -> 0.32
[2025-12-03T21:58:20.029307] 192.168.1.238:8000 -> 0.33
[2025-12-03T21:58:20.221735] 192.168.1.238:8000 -> 0.33
[2025-12-03T21:58:20.401248] 192.168.1.238:8000 -> 0.36
[2025-12-03T21:58:20.592817] 192.168.1.238:8000 -> 0.40
[2025-12-03T21:58:20.788471] 192.168.1.238:8000 -> 0.41
[2025-12-03T21:58:20.968911] 192.168.1.238:8000 -> 0.48
[2025-12-03T21:58:21.160680] 192.168.1.238:8000 -> 0.41
[2025-12-03T21:58:21.353799] 192.168.1.238:8000 -> 0.43
[2025-12-03T21:58:21.528757] 192.168.1.238:8000 -> 0.41
[2025-12-03T21:58:21.717086] 192.168.1.238:8000 -> 0.33
[2025-12-03T21:58:21.904244] 192.168.1.238:8000 -> 0.27
[2025-12-03T21:58:22.088680] 192.168.1.238:8000 -> 0.19
[2025-12-03T21:58:22.292992] 192.168.1.238:8000 -> 0.26
[2025-12-03T21:58:22.468840] 192.168.1.238:8000 -> 0.26
[2025-12-03T21:58:22.650875] 192.168.1.238:8000 -> 0.31
[2025-12-03T21:58:22.837181] 192.168.1.238:8000 -> 0.22
[2025-12-03T21:58:23.025676] 192.168.1.238:8000 -> 0.13
[2025-12-03T21:58:23.218719] 192.168.1.238:8000 -> 0.18
[2025-12-03T21:58:23.407015] 192.168.1.238:8000 -> 0.26
[2025-12-03T21:58:23.593571] 192.168.1.238:8000 -> 0.34
[2025-12-03T21:58:23.780022] 192.168.1.238:8000 -> 0.34
[2025-12-03T21:58:23.968512] 192.168.1.238:8000 -> 0.33
[2025-12-03T21:58:24.156911] 192.168.1.238:8000 -> 0.36
[2025-12-03T21:58:24.349704] 192.168.1.238:8000 -> 0.38
[2025-12-03T21:58:24.533595] 192.168.1.238:8000 -> 0.33
[2025-12-03T21:58:24.727139] 192.168.1.238:8000 -> 0.31
[2025-12-03T21:58:24.908145] 192.168.1.238:8000 -> 0.21
[2025-12-03T21:58:25.093549] 192.168.1.238:8000 -> 0.23
[2025-12-03T21:58:25.281088] 192.168.1.238:8000 -> 0.15
[2025-12-03T21:58:25.474584] 192.168.1.238:8000 -> 0.06
[2025-12-03T21:58:25.675618] 192.168.1.238:8000 -> 0.11
[2025-12-03T21:58:25.846091] 192.168.1.238:8000 -> 0.18
[2025-12-03T21:58:26.035779] 192.168.1.238:8000 -> 0.28
[2025-12-03T21:58:26.225805] 192.168.1.238:8000 -> 0.26
[2025-12-03T21:58:26.410218] 192.168.1.238:8000 -> 0.31
[2025-12-03T21:58:26.603956] 192.168.1.238:8000 -> 0.40
[2025-12-03T21:58:26.787654] 192.168.1.238:8000 -> 0.40
[2025-12-03T21:58:26.984302] 192.168.1.238:8000 -> 0.47
[2025-12-03T21:58:27.160659] 192.168.1.238:8000 -> 0.43
[2025-12-03T21:58:27.348652] 192.168.1.238:8000 -> 0.33
[2025-12-03T21:58:27.537510] 192.168.1.238:8000 -> 0.29
[2025-12-03T21:58:27.729781] 192.168.1.238:8000 -> 0.19
[2025-12-03T21:58:27.913800] 192.168.1.238:8000 -> 0.22
[2025-12-03T21:58:28.108402] 192.168.1.238:8000 -> 0.16
[2025-12-03T21:58:28.300474] 192.168.1.238:8000 -> 0.20
[2025-12-03T21:58:28.481854] 192.168.1.238:8000 -> 0.14
[2025-12-03T21:58:28.671708] 192.168.1.238:8000 -> 0.06
[2025-12-03T21:58:28.862022] 192.168.1.238:8000 -> 0.03
[2025-12-03T21:58:29.051181] 192.168.1.238:8000 -> 0.06
[2025-12-03T21:58:29.235656] 192.168.1.238:8000 -> 0.05
[2025-12-03T21:58:29.432261] 192.168.1.238:8000 -> 0.10
[2025-12-03T21:58:29.608438] 192.168.1.238:8000 -> 0.03
[2025-12-03T21:58:29.805990] 192.168.1.238:8000 -> -0.01
[2025-12-03T21:58:29.989538] 192.168.1.238:8000 -> 0.04
[2025-12-03T21:58:30.178515] 192.168.1.238:8000 -> 0.00
[2025-12-03T21:58:30.369712] 192.168.1.238:8000 -> -0.00
[2025-12-03T21:58:30.566776] 192.168.1.238:8000 -> 0.03
[2025-12-03T21:58:30.759480] 192.168.1.238:8000 -> -0.00
[2025-12-03T21:58:30.938361] 192.168.1.238:8000 -> 0.06
[2025-12-03T21:58:31.129497] 192.168.1.238:8000 -> 0.01
[2025-12-03T21:58:31.321379] 192.168.1.238:8000 -> -0.07
[2025-12-03T21:58:31.511055] 192.168.1.238:8000 -> 0.02
[2025-12-03T21:58:31.695528] 192.168.1.238:8000 -> 0.00
[2025-12-03T21:58:31.882084] 192.168.1.238:8000 -> 0.02
[2025-12-03T21:58:32.069895] 192.168.1.238:8000 -> 0.08
[2025-12-03T21:58:32.259475] 192.168.1.238:8000 -> -0.02
[2025-12-03T21:58:32.448783] 192.168.1.238:8000 -> 0.05
[2025-12-03T21:58:32.637701] 192.168.1.238:8000 -> -0.03
[2025-12-03T21:58:32.832856] 192.168.1.238:8000 -> -0.11
[2025-12-03T21:58:33.024933] 192.168.1.238:8000 -> -0.08
[2025-12-03T21:58:33.225518] 192.168.1.238:8000 -> -0.07
[2025-12-03T21:58:33.409299] 192.168.1.238:8000 -> -0.02
[2025-12-03T21:58:33.604414] 192.168.1.238:8000 -> 0.04
[2025-12-03T21:58:33.796910] 192.168.1.238:8000 -> 0.02
[2025-12-03T21:58:33.996153] 192.168.1.238:8000 -> -0.05
[2025-12-03T21:58:34.179262] 192.168.1.238:8000 -> 0.05
[2025-12-03T21:58:34.372664] 192.168.1.238:8000 -> -0.04
[2025-12-03T21:58:34.561374] 192.168.1.238:8000 -> -0.04
[2025-12-03T21:58:34.762522] 192.168.1.238:8000 -> -0.14
[2025-12-03T21:58:34.948867] 192.168.1.238:8000 -> -0.15
[2025-12-03T21:58:35.139004] 192.168.1.238:8000 -> -0.17
[2025-12-03T21:58:35.333914] 192.168.1.238:8000 -> -0.11
[2025-12-03T21:58:35.535354] 192.168.1.238:8000 -> -0.14
[2025-12-03T21:58:35.723050] 192.168.1.238:8000 -> -0.22
[2025-12-03T21:58:35.913285] 192.168.1.238:8000 -> -0.30
[2025-12-03T21:58:36.105266] 192.168.1.238:8000 -> -0.36
[2025-12-03T21:58:36.299306] 192.168.1.238:8000 -> -0.39
[2025-12-03T21:58:36.493313] 192.168.1.238:8000 -> -0.36
[2025-12-03T21:58:36.685513] 192.168.1.238:8000 -> -0.31
[2025-12-03T21:58:36.879361] 192.168.1.238:8000 -> -0.23
[2025-12-03T21:58:37.077396] 192.168.1.238:8000 -> -0.27
[2025-12-03T21:58:37.272997] 192.168.1.238:8000 -> -0.24
[2025-12-03T21:58:37.463490] 192.168.1.238:8000 -> -0.33
[2025-12-03T21:58:37.656498] 192.168.1.238:8000 -> -0.38
[2025-12-03T21:58:37.850195] 192.168.1.238:8000 -> -0.47
[2025-12-03T21:58:38.041767] 192.168.1.238:8000 -> -0.47

After running this cell:

- The socket is bound once
- A background thread is started
- Every UDP packet sent to your_PC_IP : 8050 is printed and logged into df

## Check what has been received so far

In [5]:
df.tail()

                     timestamp              sender  value
79  2025-12-03T21:58:31.321379  192.168.1.238:8000  -0.07
80  2025-12-03T21:58:31.511055  192.168.1.238:8000   0.02
81  2025-12-03T21:58:31.695528  192.168.1.238:8000   0.00
82  2025-12-03T21:58:31.882084  192.168.1.238:8000   0.02
83  2025-12-03T21:58:32.069895  192.168.1.238:8000   0.08

## Save everything to CSV

In [46]:
df.to_csv("udp_data.csv", index=False)
print("Saved to udp_data.csv")

Saved to udp_data.csv

## Stop continuous listening

When you’re done listening and logging:

In [6]:
running = False      # tell the thread to stop
sock.close()         # unblock recvfrom and close the socket
print("UDP listener stopped and socket closed.")

UDP listener stopped and socket closed.